### ISSUE TITLE
Implementation plan for HK-DOT

### ISSUE THREAD

**Issue by Blaisorblade** [Blaisorblade/dot-iris#360]
An updated version of my plan from August 2020:

- [x] stop indexing the Coq types of Dot semantic types by arity (via dependent types) (#347);
- [x] New: Limit dependency on sTEq_Eta #345
- [ ] add syntax for HK-DOT (#302)
- [ ] New: optionally: fork the syntactic type system.
- [ ] Maybe: drop (typing rules for) singleton types (?)
- [ ] enable writing syntactic values in types, for examples such as `F.F (\nu z. { A = Int })` (aka, `F Int`). This might depend on the previous step.
- [ ] Then tackle functionality of type constructors. (TODO: add the remaining steps from the plan).

**Comment by Blaisorblade** [comment]
TODO write down binary logrel on paper.
